name: ngf_organic
description: "NGF Organic - Sustainable Shop"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.3+10

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_carousel_widget: ^3.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  path_provider: ^2.1.5
  firebase_messaging: ^15.2.0
  intl: ^0.20.1
  go_router: ^14.6.3
  flutter_riverpod: ^2.6.1
  animations: ^2.0.11
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating: ^2.0.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.2
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  marquee: ^2.3.0
  http: ^1.3.0
  razorpay_flutter: ^1.3.7
  lottie: ^3.3.1
  easy_stepper: ^0.8.5+1
  flutter_rating_bar: ^4.0.1
  webview_flutter_android: ^4.3.1
  webview_flutter_platform_interface: ^2.10.0
  pdf: ^3.11.1
  open_file: ^3.3.2
  indian_currency_to_word: ^1.0.0
  smart_auth: ^3.2.0
  flutter_local_notifications: ^18.0.1
  internet_connection_checker_plus: ^2.7.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/navigation/
    - assets/animations/
    - .env
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
